// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers'
import {Header} from '../components/shared/header'
import { SidebarNavigation } from '@/components/shared/SidebarNavigation';
import { Box, Flex } from "@chakra-ui/react";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en'>
      <body>
      <Providers>
          <Flex background="#1b004c">
            <Box as="nav">
              <SidebarNavigation />
            </Box>
            <Box flex="1" >
              {children}
            </Box>
          </Flex>
        </Providers>
      </body>
    </html>
  )
}
